### ISSUE TITLE
error when running script

### ISSUE THREAD

**Issue by apoleon33** [Hyperengined/PWRS#3]
everytime I try to run PWRS.py, I got this traceback after pressing enter. It doesn't matter if i use `python` or `python3` : I got the same error for both.
```python
Traceback (most recent call last):
  File "/home/*****/PWRS/main code/PWRS.py", line 190, in <module>
    drawLoopButtons(LOOP1PUMP1BUTTON[0], LOOP1PUMP1BUTTON[1], LOOP1PUMP1BUTTON[2], LOOP1PUMP1BUTTON[3], LOOP1PUMP1BUTTON[4])
  File "/home/*****/PWRS/main code/PWRS.py", line 97, in drawLoopButtons
    screen.blit(text , (width + 50, height))
TypeError: argument 1 must be pygame.Surface, not str
```
Also I don't know if its normal, but when the UI is loading, I just see a black screen.
I use manjaro btw

**Comment by Hyperengined** [comment]
for the UI's bakack screnn, it's normal, since we haven't implemented the whole UI.

**Comment by Hyperengined** [comment]
Update !
I talked with my friend, we had the same error, it's due to the way we make or at least intend to make the buttons. Buttons wich are supposed to reflect the state of the asssociated variable : button turn red when clicked and back to green whan clicked again.

**Comment by apoleon33** [comment]
does the code now works?

**Comment by Hyperengined** [comment]
no 😏

**Comment by apoleon33** [comment]
Oh
Damn

**Comment by apoleon33** [comment]
up

**Comment by Hyperengined** [comment]
Think this problem has been solved, I leave the issue opened in case it appears again

**Comment by Hyperengined** [comment]
See the corresponding merge and PR.
issue closed
